apiVersion: apps/v1
kind: Deployment
metadata:
  name: heloself
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heloself
  template:
    metadata:
      labels:
        app: heloself
    spec:
      containers:
      - image: okteto.dev/heloself:latest
        name: heloself
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "simpledesktops.com"
        - name: Vless_UUID
          value: "8f170df1-27b5-4d9d-ae0f-9ca1412948fd"
        - name: Vless_Path
          value: "/ygs"
        - name: Vmess_UUID
          value: "8f170df1-27b5-4d9d-ae0f-9ca1412948fd"
        - name: Vmess_Path
          value: "/yhgs"
        - name: Share_Path
          value: "/renme"
